TechBlog/TechBlog/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TechBlog.Data;
using TechBlog.Models;
using TechBlog.Models.EFModels;
using TechBlog.Models.ViewModels;
using TechBlog.Services;

namespace TechBlog.Controllers
{
    public class BlogsController : Controller
    {
        private Guid userIdFake = new Guid("DEEED523-E376-4FF0-8439-06381DA087CE");
        private readonly IBlogService _blogService;
        private readonly IBlogDetailService _blogDetailService;
        private readonly IModelService<Tag> _tagService;
        public BlogsController(IBlogService blogService, IBlogDetailService blogDetailService, IModelService<Tag> tagService)
        {
            _blogService = blogService;
            _blogDetailService = blogDetailService;
            _tagService = tagService;
        }
        
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var tags = await _tagService.GetAll();
            ViewBag.SelectTags = tags.Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Name });
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,HtmlContent,ImageDisplay,Tags")] BlogPostVM blogPostVM)
        {
            var tags = await _tagService.GetAll();
            ViewBag.SelectTags = tags.Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Name });
            if (ModelState.IsValid)
            {
                var idCurrentUser = new Guid(User.FindFirst(claim => claim.Type == System.Security.Claims.ClaimTypes.NameIdentifier)?.Value);
                if (await _blogService.Create(idCurrentUser, blogPostVM))
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Create blog failed!!!");
                    return View(blogPostVM);
                }
            }
            return View(blogPostVM);
        }

        public async Task<IActionResult> Detail(Guid? id)
        {
            if (!id.HasValue)
            {
                return NotFound("Product Id Not Found");
            }

            return View(await _blogDetailService.GetByBlogId(id.GetValueOrDefault()));
        }
    }
}

TechBlog/TechBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("ScriptsTop", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand btn btn-primary" href="~/">TECH BLOG</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.Name != null)
                        {
                            <li class="nav-item active mx-3">
                                <h5 class="nav-link">Hello @User.Identity.Name!!!</h5>
                            </li>
                            <li class="nav-item active mx-3">
                                <a class="nav-link btn btn-outline-light" asp-action="Create" asp-controller="Blogs">Post A Blog</a>
                            </li>
                            <li class="nav-item active mx-3">
                                <a class="nav-link btn btn-warning" asp-action="Logout" asp-controller="Accounts">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item active mx-3">
                                <a class="nav-link btn btn-outline-success" asp-action="Login" asp-controller="Accounts">Login</a>
                            </li>
                            <li class="nav-item active mx-3">
                                <a class="nav-link btn btn-outline-light" asp-action="Register" asp-controller="Accounts">Register</a>
                            </li>
                        }
                    </ul>

                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @await Component.InvokeAsync("TagMenu")
        <main role="main" class="my-3 row">

            @RenderBody()
            <aside class="col-sm-3 ">
                <div class="p-3 mb-3 text-center bg-light">
                    <img class="rounded-circle" src="~/images/user/admin.jpg" alt="Generic placeholder image" width="140" height="140">
                    <h2 class="h2">About me</h2>
                    <p>Nguyen Hieu Trung</p>
                    <nav class="d-flex px-5">
                        <a href="/"><img src="~/images/icon/facebook.svg" alt="Facebook" class="w-50" /></a>
                        <a href="/"><img src="~/images/icon/skype.svg" alt="Skype" class="w-50" /></a>
                        <a href="/"><img src="~/images/icon/linkedin.svg" alt="Linkedin" class="w-50" /></a>
                    </nav>
                </div>
                <div class="p-3 mb-3 text-center bg-light">
                    <h2>Archives</h2>
                    <ol class="list-unstyled mb-0">
                        <li><a href="#">March 2014</a></li>
                        <li><a href="#">February 2014</a></li>
                        <li><a href="#">January 2014</a></li>
                        <li><a href="#">December 2013</a></li>
                        <li><a href="#">November 2013</a></li>
                        <li><a href="#">October 2013</a></li>
                        <li><a href="#">September 2013</a></li>
                    </ol>
                </div>
            </aside>
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TechBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>